version: "3"

services:
  backend:
    ports:
      - "3001:3001"
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      - DB_HOST=my-postgres-prod
    depends_on:
      - my-postgres-prod

  frontend:
    ports:
      - "80:80"
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://backend:3001

  my-postgres-prod:
    image: postgres:16
    container_name: my-postgres-prod
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
