version: "3"

services:
  backend:
    ports:
      - "3001:3001"
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=my-postgres
    depends_on:
      - my-postgres
    networks:
      - app-network

  frontend:
    ports:
      - "5173:5173"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:3001
    networks:
      - app-network

  my-postgres:
    image: postgres:16
    container_name: my-postgres
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:
networks:
  app-network:
    driver: bridge
