version: "3"

services:
  backend:
    ports:
      - "3001:3001"
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=my-postgres
    depends_on:
      - my-postgres

  frontend:
    ports:
      - "4173:4173"
    build:
      context: ./frontend
      dockerfile: Dockerfile

  my-postgres:
    image: postgres:16
    container_name: my-postgres
    env_file:
      - backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
