version: "3"

# doesnt work
services:
  backend:
    ports:
      - "3001:3001"
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - my-postgres

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile

  my-postgres:
    image: postgres:16
    container_name: my-postgres
    env_file:
      - backend/.env
    # environment:
    #   POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
# networks:
#   mynw:
# volumes:
#   pgdata:
#     name: pgdata
