apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: europe-west2-docker.pkg.dev/bomb-3eb03/my-repo/test_gke_k8s-vue-app
        ports:
        - containerPort: 80