apiVersion: v1
kind: Service
metadata:
  name: pevnstore-frontend
spec:
  type: LoadBalancer
  selector:
    app: pevnstore-frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
